name: ecommerce
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

#----------Packages --------#

dependencies:
  flutter:
    sdk: flutter

#------------utility packages -------#
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.3.6
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Icons

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

# State Management
get: ^4.6.6

# Product Specific

#--------------- Packages end -----------#

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # Local Assets -----
  assets:
   - assets/icons/
   - assets/icons/brands/
   - assets/images/
   - assets/logos/
   - assets/animations/
   - assets/products/
   - assets/banners/
   - assets/payment/

# Local Fonts -------

